name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'

      - name : Package jar
        run : mvn clean install

      - name : Verify Jar File
        run : ls -al target/

      - name : Copy to /
        run : cp target/app.jar . && ls

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name : Build the image
        run : | 
          docker build -t olymahmudmugdho/react-with-spring-boot .

      - name : Push the image
        run: |
          docker push olymahmudmugdho/react-with-spring-boot
